### ISSUE TITLE
Incorrect version for package by default

### ISSUE THREAD

**Issue by wcoder** [praeclarum/FuGetGallery#106]
Hi @praeclarum thanks for the awesome tool!

After last using looks as a bug:

Steps:
- Open Xamarin.Forms: https://www.fuget.org/packages/Xamarin.Forms

Expected:
- The latest version of the package (4.5+)

Actual:
<img width="662" alt="Screen Shot 2020-03-25 at 11 15 50 AM" src="https://user-images.githubusercontent.com/766193/77649849-92a26c00-6f7b-11ea-9323-d23bdbadf5dc.png">

Can be related to #105, #63

**Comment by praeclarum** [comment]
Yes,

I think I’m just going to switch to date ordering. Version numbers are insane these days :-)

-Frank

**Comment by praeclarum** [comment]
Working on this now

**Comment by praeclarum** [comment]
- [ ] Fix ordering
- [ ] Make sure latest packages are listed
