### ISSUE TITLE
Packages with .Config suffix show an error

### ISSUE THREAD

**Issue by cndouglas** [praeclarum/FuGetGallery#122]
Example: https://www.fuget.org/packages/NLog.Config

The page for this package gives `404 not found` with the following message: `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

The page loads fine on nuget.org: https://www.nuget.org/packages/NLog.Config

**Comment by praeclarum** [comment]
Oh IIS. I will need someone familiar with it to help get it to stop blocking things.
