### ISSUE TITLE
System.Reflection.MetadataLoadContext is broken

### ISSUE THREAD

**Issue by chkn** [praeclarum/FuGetGallery#124]
Try to load the fuget page for `System.Reflection.MetadataLoadContext` and note that it doesn't work.

**Comment by svick** [comment]
Can you be more specific? It seems to work fine for me:

![](https://user-images.githubusercontent.com/287848/101992986-2907f080-3cb7-11eb-9e8c-1033d2e4a6ef.png)

**Comment by chkn** [comment]
Just checked it again and it does indeed appear to be working now, so maybe just a transient failure.
