### ISSUE TITLE
System.OutOfMemoryException?

### ISSUE THREAD

**Issue by waheedsayed** [praeclarum/FuGetGallery#138]
Hi,

First, I'd like to thank you for this helpful tool, sometimes I'd like to check the content of a package on the fly, so this comes in handy. I was already inspecting couple of AWS nuget packages then suddenly I got this error about System.OutOfMemoryException, so I wanted to notify you probably there's a memory leak that requires investigation.

_Note_: It seems a cached result! When I change the package name in search, I get results.
So if I used `SimpleNotificationService` instead of `AWSSDK.SimpleNotificationService` I get results.

> # 
![Screen Shot 2021-03-04 at 12 22 22 pm](https://user-images.githubusercontent.com/194151/109896231-b110fb80-7ce4-11eb-9cb6-1b30a551e95c.png)

**Comment by i2van** [comment]
The same is for [LPRun](https://www.fuget.org/packages/LPRun/6.13.13) package. This package contains ~40MB of binaries.

**Comment by praeclarum** [comment]
Thanks to #139, the site now handles these packages. Please open a new bug if you run into this again.
