### ISSUE TITLE
Showing unlisted packages

### ISSUE THREAD

**Issue by wekempf** [praeclarum/FuGetGallery#23]
When I saw fuget.org announced on Twitter, I thought I'd explore what it does using one of my own projects (oh, the vanity). The first thing that stood out was that my embarrassing goof was on full display here. :(

[Testify](https://fuget.org/packages/Testify)

See, at one point in a rush to get out a bug fix I transposed some numbers when specifying the version. The automated build published this to NuGet.org before I noticed the mistake. You can't really delete packages from NuGet.org, the best you can do is "unlist" them, which I did, and then built and pushed with the correct version. On NuGet.org if you're not an owner, you don't see unlisted packages, but fuget.org shows them.

**Comment by praeclarum** [comment]
Ahhhh, you're right I don't check for that flag, my mistake!

Hehe, we all unlist packages - part of the job ;-)

**Comment by loic-sharma** [comment]
Determining whether a package is listed/unlisted can be tricky using V3 APIs. The registration doesn't store whether a package is listed or unlisted, you'll need to follow the [`catalogEntry`'s `@id` property](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#catalog-entry) to get the URI to the catalog leaf for that specific version of the package. From that document, you can use the [`published` and `listed` properties](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#catalog-entry) to determine whether a pacakge is listed.
