### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by SeriousM** [praeclarum/FuGetGallery#27]
Hi!
This is a great addition to nuget, thank you very much.
Would it be possible to add a sorting by downloads?
This is a missing feature on nuget.org and I thought this would make fuget.org even better!

**Comment by praeclarum** [comment]
Ah yes, in the search screen?

**Comment by SeriousM** [comment]
Yes please! Do you think a distinction between total downloads and total
downloads of recent 3 releases makes sense?

**Comment by loic-sharma** [comment]
Ideally, search would favor packages with lots of recent downloads in the past X weeks. This will need work by the nuget.org team as we doesn't expose enough information for third-parties to do these calculations. In case someone is interested in helping out, you would need to update the [Stats.CreateAzureCdnWarehouseReports project](https://github.com/NuGet/NuGet.Jobs/tree/master/src/Stats.CreateAzureCdnWarehouseReports) 😉 

See https://github.com/NuGet/NuGetGallery/issues/695

**Comment by SeriousM** [comment]
I see @loic-sharma, thanks for the information!
