### ISSUE TITLE
Detail pages for packages that end in .cs respond with 404

### ISSUE THREAD

**Issue by mganss** [praeclarum/FuGetGallery#49]
Packages whose name ends in ".cs" show in search results but detail pages respond with a 404.

Examples:
- https://www.fuget.org/packages/Glob.cs
- https://www.fuget.org/packages/Humanizer.Core.cs
- https://www.fuget.org/packages/Underscore.cs

**Comment by mikkelbu** [comment]
This is no longer an issue. At least the above examples all show without any problems.

**Comment by bgrainger** [comment]
This may have been a duplicate of https://github.com/praeclarum/FuGetGallery/issues/122 and fixed by https://github.com/praeclarum/FuGetGallery/pull/135.
