### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by svick** [praeclarum/FuGetGallery#62]
The fuget.org site is currently down, displaying the error:

> Error 403 - This web app is stopped.

![](https://user-images.githubusercontent.com/287848/56649168-eda15400-6684-11e9-853e-7318de994318.png)

**Comment by silkfire** [comment]
Same here. What's going on?

**Comment by loic-sharma** [comment]
Looks like the Azure subscription ran out of credits: https://twitter.com/praeclarum/status/1121143644231069696?s=20

**Comment by japj** [comment]
And it is up again https://mobile.twitter.com/praeclarum/status/1121929007505666049
