### ISSUE TITLE
Package page shows outdated version by default

### ISSUE THREAD

**Issue by cmeeren** [praeclarum/FuGetGallery#63]
Check out [Fable.Core](https://www.fuget.org/packages/Fable.Core). The latest version (as can be seen in the dropdown menu, indicated by a red arrow) is 3.0.0, released April 16th. However, the automatically selected version is 3.0.0-beta-006, released April 12th.

![image](https://user-images.githubusercontent.com/7766733/57097767-dca5b200-6d18-11e9-934f-69520bfc9300.png)

**Comment by TylerBrinkley** [comment]
@praeclarum would you be open to sorting this by publish time instead? Currently it's sorting by version number as can be seen [here](https://github.com/praeclarum/FuGetGallery/blob/master/Pages/packages/details.cshtml#L187).

**Comment by svick** [comment]
@TylerBrinkley [That's not how semver versions should be ordered.](https://semver.org/#spec-item-11)

The relevant (incorrect) code is here:

https://github.com/praeclarum/FuGetGallery/blob/b49ddc852dfedf46c666398138376891b835250f/Data/PackageVersions.cs#L158-L169

**Comment by TylerBrinkley** [comment]
@svick good call. I was assuming the version was just a string not a full type.

**Comment by loic-sharma** [comment]
NuGet client code can be found here:

https://github.com/NuGet/NuGet.Client/blob/01e4463d276961b71bd65d172fa3907e823cd49f/src/NuGet.Core/NuGet.Versioning/VersionComparer.cs#L127-L212
