### ISSUE TITLE
Old versions of packages disappeared recently

### ISSUE THREAD

**Issue by MaceWindu** [praeclarum/FuGetGallery#71]
I've noticed that for about two last weeks, old versions of nugets disappeared from site, which makes API diff functionality unusable, because there is no previous version you can select.

Some exaples:
https://www.fuget.org/packages/FirebirdSql.Data.FirebirdClient/ - offers only recently released version 7.0.0
https://www.fuget.org/packages/linq2db - offers only 2.9.0 and 2.8.1

**Comment by MaceWindu** [comment]
Looks like something changed in nuget API, as this is what `https://api.nuget.org/v3/registration3/<package>/index.json` request returns.

**Comment by praeclarum** [comment]
I believe all pages are loaded now. Please reopen if you have a missing package.
