### ISSUE TITLE
Why are some versions not visible? 

### ISSUE THREAD

**Issue by 304NotModified** [praeclarum/FuGetGallery#75]
Why are some versions not visible on FuGet, but visible on NuGet? 3.0.0-x are missing for Microsoft.Extensions.Logging:

NuGet: - https://www.nuget.org/packages/Microsoft.Extensions.Logging/

![image](https://user-images.githubusercontent.com/5808377/64495077-81229c80-d295-11e9-97a8-d3c489c1ff08.png)

FuGet: - https://www.fuget.org/packages/Microsoft.Extensions.Logging/

![image](https://user-images.githubusercontent.com/5808377/64495089-97305d00-d295-11e9-9741-e4cfc72ae0a6.png)

**Comment by 304NotModified** [comment]
Maybe this is related? (from https://www.nuget.org/packages/Microsoft.Extensions.Logging/3.0.0-preview9.19423.4)

![image](https://user-images.githubusercontent.com/5808377/64495156-8af8cf80-d296-11e9-9117-8d64bda64b0d.png)

**Comment by loic-sharma** [comment]
This line seems to be the issue:

https://github.com/praeclarum/FuGetGallery/blob/25a700a30937e9b754230b1fa3a6248f3b466d1e/appsettings.json#L9

Instead, it should be:

```
"VersionsUrlFormat": "https://api.nuget.org/v3/registration3-gz-semver2/{0}/index.json", 
```

Background: the current `VersionsUrlFormat` uses the `RegistrationsBaseUrl/3.0.0-beta` resource, which excludes SemVer 2.0.0 packages. You'll need to use the `RegistrationsBaseUrl/3.6.0` resource to include SemVer 2.0.0 packages. For more information, please refer to the [Package Metadata resource documentation](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#versioning).

**Comment by loic-sharma** [comment]
By the way, I've been working on an SDK that handles all the nitty gritties of the NuGet protocol for you: https://loic-sharma.github.io/BaGet/tools/sdk/

Listing all versions would be as simple as:

```csharp
NuGetClient client = new NuGetClient("https://api.nuget.org/v3/index.json");

IReadOnlyList<NuGetVersion>> versions = await client.ListPackageVersionsAsync("Newtonsoft.Json");

foreach (NuGetVersion version in versions)
{
    Console.WriteLine($"Found version: {version}");
}
```

@praeclarum Let me know if you're interested in using it! It's still a WIP, so I'd love feedback before I ship it 😄

**Comment by bgrainger** [comment]
I've pushed a commit that fixes this here: https://github.com/bgrainger/FuGetGallery/commit/192f296e00c2a618f27805d80e89d7b7ca09842c
